# Basics of Numpy

## Introductory Lesson: Array Basics

### Mark Braxton

#### March 2022

In [6]:
#import NumPy

import numpy as np

# Part 1: Arrays

In [8]:
#Create a few sample lists

gpa = [3.1, 3.3, 4.0, 3.5, 2.5, 2.8, 2.0]
age = [13, 15, 17, 12, 13, 16, 14]

In [9]:
#Changing lists to numpy arrarys

gpa_array = np.array(gpa)
age_array = np.array(age)

In [14]:
#Display arrays

print("gpa_array:", gpa_array, "age_array: ", age_array)

gpa_array: [3.1 3.3 4.  3.5 2.5 2.8 2. ] age_array:  [13 15 17 12 13 16 14]


In [16]:
#Checking list vs. array type with built in function

print(type(gpa))
print(type(gpa_array))
print(type(age))
print(type(age_array))

<class 'list'>
<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.ndarray'>


In [41]:
#Array with multiple rows
#Creating an Array with our GPA and Age lists

Data_Array = np.array([gpa,age])
Data_Array

#Notice the ages are now in the form of integers since the GPA is in that form. The array function will put the values as the same integer type

array([[ 3.1,  3.3,  4. ,  3.5,  2.5,  2.8,  2. ],
       [13. , 15. , 17. , 12. , 13. , 16. , 14. ]])

In [59]:
#Showing Various Indices of our Array

#Showing the first row

print("First Row of Array:", Data_Array[0])

#Showing the first column

print("First Column of Array:", Data_Array[:,0])

#Showing the second row intersected with the 5th and 6th columns

print("Selection of the second row and only the elements from the 3rd and 4th columns:", Data_Array[1,2:4])

#Notice how the columns are selected. The index of 1 in the above code refers to the second row of the Data Array.

#The 2:4 index refers to starting at the 3rd column (remember, index 0 is column 1) going to index 4, which doesn't include index 4. It stops at index 3, which is the 4th column of the Array

First Row of Array: [3.1 3.3 4.  3.5 2.5 2.8 2. ]
First Column of Array: [ 3.1 13. ]
Selection of the second row and only the elements from the 3rd and 4th columns: [17. 12.]


In [66]:
#You can creating an array with a set number of sequential elements

Array_1 = np.arange(5)

print("Array created with arange:", Array_1)

#Creating an array for operations

Array_2 = np.array([0, -1, -2, -3, -4])

print("Array created manually:", Array_2)

#You can perform operations on Arrays and binary operations on arrays. Note: the arrays need to have the same number of elements to do pairwise operations.

print("Adding different arrays:", Array_1 + Array_2)

#Performing an operation on Array_1 
print("Multiplying Array_1 by four:", Array_1*4)

Array created with arange: [0 1 2 3 4]
Array created manually: [ 0 -1 -2 -3 -4]
Adding different arrays: [0 0 0 0 0]
Multiplying Array_1 by four: [ 0  4  8 12 16]


In [75]:
#Finding values in an array by comparision searches

#Displaying values less than 0

print("Values in Array_1 less than zero:", Array_2[Array_2 < 0])

Values in Array_1 less than zero: [-1 -2 -3 -4]


In [92]:
#Creating an array for practice

Array_3 = np.arange(10)
print(Array_3)

#Sum of values in Array_3
print("Sum of Array_3:", Array_3.sum())

#Min value in Array_3
print("Min of Array_3:", Array_3.min())

#Mean of Array_3
print("Mean of Array_3 =", Array_3.mean())

#Median of Array_3
print("Median of Array_3 =", np.median(Array_3))

[0 1 2 3 4 5 6 7 8 9]
Sum of Array_3: 45
Min of Array_3: 0
Mean of Array_3 = 4.5
Median of Array_3 = 4.5


In [113]:
#Array concatenation
#Array must have the same dimensions when catecating along the rows or columns

Array_4 = np.arange(6)
Array_5 = np.arange(6)*2

print("Array_4:", Array_4,"Array_5:", Array_5)

#Determine the shape of an array

print("The shape of Array_4 is:", Array_4.shape)
print("The shape of Array_5 is:", Array_5.shape)

#concatenation of Array_4 and Array_5, the default axis here is 0, which puts the arrays side by side

print("Concatenation of Array_4 and Array_5:", np.concatenate([Array_4,Array_5]))

#creating two new 2-D arrays

Array_6 = np.array([[0,1,2,3],[4,5,6,7]])
Array_7 = np.array([[8,9,10,11],[12,13,14,15]])

#concatenation of 2-D arrays

print("Below is the concatenation of Array_6 and Array_7 along the default x = 0 axis (stack):")
print(np.concatenate([Array_6,Array_7]))

print("Below is the concatenation of Array_6 and Array_7 along the x = 1 axis (side by side)")
print(np.concatenate([Array_6,Array_7], axis = 1))

Array_4: [0 1 2 3 4 5] Array_5: [ 0  2  4  6  8 10]
The shape of Array_4 is: (6,)
The shape of Array_5 is: (6,)
Concatenation of Array_4 and Array_5: [ 0  1  2  3  4  5  0  2  4  6  8 10]
Below is the concatenation of Array_6 and Array_7 along the default x = 0 axis (stack):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Below is the concatenation of Array_6 and Array_7 along the x = 1 axis (side by side)
[[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]


In [148]:
#You can reshape an array to help with array operations or just to reshape the array in general

#Creation of new Array_8

Array_8 = np.arange(20)

print("Array_8 arange defalut:", Array_8)

#reshape into a rectangular array

print("Below is Array_8 reshaped into a rectangular array:")
Array_9 = Array_8.reshape(5,4)
print(Array_9)

#We can do the opposite of concatenation too with the split operation:
#Let's split a 2-D array into two array by first creating a new array

print("Below, we created a new array with arange function and reshaped the array with the reshape function")
Array_10 = np.arange(10).reshape(2,5)
print(Array_10)
print("Now we are going to use the array_split function to put the array into 2 different arrays:")
print(np.array_split(Array_10, 2))

#The last thing we are going to do is split arrays by both columns and rows respectively
Array_11 = np.arange(60).reshape(10,6)
print("Below is our Array_11 with 10 rows and 6 columns:")
print(Array_11)
print("Now we will split the array by stacked rows (vsplit()):")
np.vsplit(Array_11,2)

Array_8 arange defalut: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Below is Array_8 reshaped into a rectangular array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Below, we created a new array with arange function and reshaped the array with the reshape function
[[0 1 2 3 4]
 [5 6 7 8 9]]
Now we are going to use the array_split function to put the array into 2 different arrays:
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]
Below is our Array_11 with 10 rows and 6 columns:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]
Now we will split the array by stacked rows (vsplit()):


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]])]

In [149]:
print("Now we will split the array by columns (hsplit()):")
np.hsplit(Array_11,2)

Now we will split the array by columns (hsplit()):


[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32],
        [36, 37, 38],
        [42, 43, 44],
        [48, 49, 50],
        [54, 55, 56]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35],
        [39, 40, 41],
        [45, 46, 47],
        [51, 52, 53],
        [57, 58, 59]])]